### PR TITLE
Update .gitignore and Makefile

### PR DESCRIPTION
**Pull request by frno7**

### CODE REVIEW

**Comment by frno7** [comment]
I’ve made more extensive changes in [lib/sndh/ice.c](https://github.com/frno7/psgplay/blob/21e37e9304c50357f80b7eba5be5a0d16c48d5c3/lib/sndh/ice.c) in [psgplay](https://github.com/frno7/psgplay).

There is also a separate [pack-ice-v3](https://github.com/frno7/pack-ice/tree/pack-ice-v3) branch with original Public Domain [Pack Ice v3](https://dhs.nu/news.php?t=single&ID=790) m68k assembler source code, but I haven’t verified that it works or even assembles. I’m considering using the assembler variant for a forthcoming Atari PSG player, depending on how it performs compared to the C variant.

**Comment by larsbrinkhoff** [comment]
Thanks!

My main concern is whether it works well.  Many years ago, someone tried to use it with mixed results.  Maybe it was the packer that didn't work.

**Comment by frno7** [comment]
I’ve decrunched about 4877 SNDH files from the [SNDH archive 4.7](http://sndh.atari.org/) and that seems to work, although there are no checksums or similar so one cannot be completely sure. I’ve been told that a forthcoming version of the SNDH archive will no longer compress the files, and at that point Pack Ice will be deprecated in psgplay.

Would you like to pick up the separate [pack-ice-v3](https://github.com/frno7/pack-ice/tree/pack-ice-v3) branch with the original Public Domain [Pack Ice v3](https://dhs.nu/news.php?t=single&ID=790) m68k assembler source code too?

**Comment by larsbrinkhoff** [comment]
Sure yes, that would be a good idea.

**Comment by frno7** [comment]
Hmm... I probably should have done `chmod a+x ICE_3_0.PRG` as it is an executable program after all. All files are verbatim from [axe.zip](http://files.dhs.nu/files_source/axe.zip) otherwise.

**Comment by larsbrinkhoff** [comment]
Can you please submit a pull request?

I made the C version from a disassembled listing of the original unpacker.  Too bad I no longer have the listing, so I can't add it as reference material.

**Comment by frno7** [comment]
GitHub apparently doesn’t permit creating a pull request for the [pack-ice-v3 ](https://github.com/frno7/pack-ice/tree/pack-ice-v3) branch that isn’t an ancestor of yours.

> I made the C version from a disassembled listing of the original unpacker. Too bad I no longer have the listing, so I can't add it as reference material.

With a bit of m68k tooling there is at least excellent opportunities to verify your C variant against the assembly original!

**Comment by larsbrinkhoff** [comment]
FIRE and ICE, huh?  Was this written by George R. R. Martin?

**Comment by frno7** [comment]
I’ve now updated the [pack-ice-v3](https://github.com/frno7/pack-ice/tree/pack-ice-v3) branch with some missing pieces I found in [ST NEWS volume 5 issue 2](https://st-news.com/issues/st-news-volume-5-issue-2/), especially [ICE_UNP2.S](https://github.com/frno7/pack-ice/blob/pack-ice-v3/ICE_UNP2.S). A useful property of the original assembly code with a memory constrained Atari ST is that decrunching can be done _almost_ in-place, as Axe of Delight says:

> Please check out that the target address is at least 120 (`$78`) bytes higher than the source address. Otherwise, you might overwrite the original data.

The C variant [ice_decrunch.c](https://github.com/larsbrinkhoff/pack-ice/blob/master/ice_decrunch.c) verifiably does not support this. However, a margin of 4096 bytes does work with all the SNDH files in version 4.7 of the archive.

More Pack-Ice source code can be obtained at [DEMOZOO Axe](https://demozoo.org/sceners/37767/) and `ftp://fujiology.untergrund.net/users/ltk_tscc/fujiology/ST/D/DELIGHT/`.

**Pull request merged**
